const stage = document.getElementById('stage');
const castList = document.getElementById('castList');
const tracks = document.getElementById('tracks');
const emptyHint = document.getElementById('emptyHint');
const recordTitle = document.getElementById('recordTitle');
const figures = [
  { id:'maya', name:'Maya', role:'protagonist', color:'#f26b45', skin:'#f8c38c', x:38, y:80, icon:'●' },
  { id:'visitor', name:'Visitor', role:'mystery guest', color:'#6d68c9', skin:'#e8b895', x:67, y:80, icon:'✦' }
];
let history = [], beats = [], playing = false, recording = false, playbackFrame = 0;

function figureSvg(f){ return `<svg viewBox="0 0 60 112" aria-hidden="true"><circle cx="30" cy="18" r="12" fill="${f.skin}" stroke="${f.color}" stroke-width="3"/><path d="M18 16 Q30 2 42 16" fill="none" stroke="${f.color}" stroke-width="6" stroke-linecap="round"/><path d="M30 30 L30 72 M30 43 L10 57 M30 43 L50 52 M30 72 L14 101 M30 72 L47 99" fill="none" stroke="${f.color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="26" cy="18" r="1.5" fill="#41392f"/><circle cx="35" cy="18" r="1.5" fill="#41392f"/></svg>` }
function renderCast(){ castList.innerHTML=figures.map((f,i)=>`<div class="cast-item ${i===0?'active':''}" data-id="${f.id}"><span class="cast-avatar" style="background:${f.color}20;color:${f.color}">${f.icon}</span><div><div class="cast-name">${f.name}</div><div class="cast-role">${f.role}</div></div><span class="eye">◉</span></div>`).join(''); }
function renderFigures(){ document.querySelectorAll('.figure').forEach(el=>el.remove()); figures.forEach(f=>{ const el=document.createElement('div'); el.className='figure'; el.dataset.id=f.id; el.style.left=f.x+'%'; el.style.top=f.y+'%'; el.innerHTML=`<span class="figure-name">${f.name}</span>${figureSvg(f)}`; stage.appendChild(el); drag(el,f); }); emptyHint.style.display=figures.length?'none':'grid'; }
function renderTracks(){ tracks.innerHTML=figures.map(f=>`<div class="track"><div class="track-label"><i style="background:${f.color}"></i>${f.name}</div><div class="beats">${beats.filter(b=>b.id===f.id).map(b=>`<div class="beat" style="left:${b.time*14}%;width:${Math.max(10,b.duration*14)}%">move</div>`).join('')}</div></div>`).join(''); }
function drag(el,f){ let start, moved=false; el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId); start={x:e.clientX,y:e.clientY,fx:f.x,fy:f.y,t:performance.now()}; history.push({f,x:f.x,y:f.y}); if(recording) recordTitle.textContent='Recording movement…'; el.style.zIndex=8;}); el.addEventListener('pointermove',e=>{if(!start)return; moved=true; const r=stage.getBoundingClientRect(); f.x=Math.max(8,Math.min(92,start.fx+(e.clientX-start.x)/r.width*100)); f.y=Math.max(33,Math.min(88,start.fy+(e.clientY-start.y)/r.height*100)); el.style.left=f.x+'%';el.style.top=f.y+'%';}); el.addEventListener('pointerup',()=>{if(!start)return; if(moved && recording){beats.push({id:f.id,time:Math.min(5.7,Math.max(0,(f.x-8)/84*5.7)),duration:.7,from:{x:start.fx,y:start.fy},to:{x:f.x,y:f.y}}); renderTracks();} start=null; moved=false; if(recording) recordTitle.textContent='Recording — keep directing';}); }
function addFigure(){const n=figures.length+1; figures.push({id:'extra'+n,name:'Figure '+n,role:'new character',color:'#e0a63e',skin:'#f0bd8b',x:50,y:80,icon:'+'});renderCast();renderFigures();renderTracks();}
function toggleRecord(){recording=!recording;document.getElementById('recordText').textContent=recording?'Stop recording':'Record scene';document.getElementById('recordBtn').classList.toggle('is-recording',recording);recordTitle.textContent=recording?'Recording — drag a character':'Ready — press Record';}
function togglePlay(){playing=!playing;document.getElementById('playText').textContent=playing?'Pause scene':'Play scene';document.querySelector('.play-icon').textContent=playing?'Ⅱ':'▶';document.querySelector('.record-dot').style.background=playing?'#f26b45':'#d8d1c5';if(playing){playbackFrame=0;const tick=()=>{if(!playing)return;playbackFrame+=.03;beats.forEach((b)=>{if(!b.from||!b.to)return;const f=figures.find(x=>x.id===b.id), progress=Math.max(0,Math.min(1,(playbackFrame-b.time)/b.duration));if(f&&progress>0){f.x=b.from.x+(b.to.x-b.from.x)*progress;f.y=b.from.y+(b.to.y-b.from.y)*progress;const el=document.querySelector(`[data-id="${f.id}"].figure`);if(el){el.style.left=f.x+'%';el.style.top=f.y+'%';}}});document.getElementById('duration').textContent='00:'+String(Math.min(6,Math.floor(playbackFrame))).padStart(2,'0');if(playbackFrame>6){playing=false;document.getElementById('playText').textContent='Play scene';return}requestAnimationFrame(tick)};tick();}}
document.getElementById('addFigure').onclick=addFigure;document.getElementById('recordBtn').onclick=toggleRecord;document.getElementById('playBtn').onclick=togglePlay;document.getElementById('addBeat').onclick=()=>{if(figures[0]){beats.push({id:figures[0].id,time:1.3,duration:.7,from:{x:figures[0].x,y:figures[0].y},to:{x:figures[0].x+8,y:figures[0].y-8}});renderTracks();}};document.getElementById('undoBtn').onclick=()=>{const last=history.pop();if(last){last.f.x=last.x;last.f.y=last.y;renderFigures();renderTracks();}};document.getElementById('clearBtn').onclick=()=>{beats=[];renderTracks();};document.getElementById('backgroundBtn').onclick=()=>{stage.classList.toggle('sunset');};document.getElementById('newScene').onclick=()=>{const count=document.querySelectorAll('.saved-scene').length+1;const scene=document.createElement('button');scene.className='saved-scene';scene.innerHTML=`<span>${String(count).padStart(2,'0')}</span><span>New scene ${count}</span><em>●</em>`;document.getElementById('savedScenes').appendChild(scene);};document.getElementById('focusBtn').onclick=()=>stage.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('duplicateBtn').onclick=()=>alert('Scene duplicated — ready for your next take.');document.getElementById('exportBtn').onclick=()=>alert('Storyboard export is ready to connect to your preferred format.');document.getElementById('saveBtn').onclick=e=>{e.currentTarget.textContent='Saved ✓';document.querySelector('.project-name small').textContent='• saved just now';setTimeout(()=>e.currentTarget.textContent='Save scene',1200)};document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();togglePlay()}if(e.key.toLowerCase()==='r')toggleRecord()});
renderCast();renderFigures();renderTracks();
